---
beaker_bucket: /tmp
beaker_auth_bucket: "{{ beaker_bucket + '/' + 'auth' + '/' }}"
beaker_kickstart_bucket: "{{ beaker_bucket + '/' + 'ks' + '/' }}"
beaker_kickstart: "{{ beaker_kickstart_bucket + beaker_kickstart_file }}"
beaker_kickstart_file: "{{ inventory_hostname_short + '_ks.cfg' }}"
beaker_keytab: lab.keytab
beaker_keytab_principal: labuser
beaker_keytab_copy_to: "{{ beaker_auth_bucket + beaker_keytab }}"
beaker_hub: https://beaker.hub.com
beaker_nfsserver: nfs-server-url
beaker_ibm_imm_map:
  - { name: host5.lab.example.com, mgmt: host5-imm.mgmt.lab.example.com }
  - { name: host6.example.com, mgmt: host6-imm.mgmt.lab.example.com }
  - { name: host7.example.com, mgmt: ceph7-imm.mgmt.example.com }
beaker_dell_idrac_map:
  - { name: ceph8.example.com, mgmt: ceph8-drac.mgmt.example.com }
  - { name: ceph9.example.com, mgmt: ceph9-drac.mgmt.example.com }
  - { name: ceph10.example.com, mgmt: ceph10-drac.mgmt.example.com }
  - { name: ceph11.example.com, mgmt: ceph11-drac.mgmt.example.com }
  - { name: ceph12.example.com, mgmt: ceph12-drac.mgmt.example.com }
  - { name: ceph13.example.com, mgmt: ceph13-drac.mgmt.example.com }
  - { name: ceph14.example.com, mgmt: ceph14-drac.mgmt.example.com }
beaker_rhel_release_id:
  - { name: "9.4", id: "0", nfsdir: /rhel-9/RHEL-9/9.4.0/BaseOS/x86_64/os/ }
  - { name: "9.3", id: "0", nfsdir: /rhel-9/RHEL-9/9.3.0/BaseOS/x86_64/os/ }
  - { name: "9.2", id: "0", nfsdir: /rhel-9/RHEL-9/9.2.0/BaseOS/x86_64/os/ }
  - { name: "8.8", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.8.0/BaseOS/x86_64/os/ }
  - { name: "8.7", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.7.0/BaseOS/x86_64/os/ }
  - { name: "8.6", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.6.0/BaseOS/x86_64/os/ }
  - { name: "8.5", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.5.0/BaseOS/x86_64/os/ }
  - { name: "8.4", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.4.0/BaseOS/x86_64/os/ }
  - { name: "8.2", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.2.0/BaseOS/x86_64/os/ }
  - { name: "8.1", id: "0", nfsdir: /rhel-6-7-8/rhel-8/RHEL-8/8.1.0/BaseOS/x86_64/os/ }
