---
- name: Ok la oss ha det litt gøy!
  block:
    - name: Set up profile stuff
      become: true
      become_user: root
      block:
        - name: Profile-d
          ansible.builtin.copy:
            src: "{{ item.name }}"
            dest: "{{ item.place }}"
            mode: "0444"
            seuser: system_u
            serole: object_r
            setype: etc_t
            selevel: s0
          loop: "{{ baseos_file_list }}"

        - name: Gnupg
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "/home/{{ ansible_user }}/.gnupg/{{ item }}"
            mode: "0444"
            seuser: system_u
            serole: object_r
            setype: etc_t
            selevel: s0
          loop: "{{ baseos_gpg_files }}"

    - name: Setting up GPG
      become: true
      become_user: "{{ ansible_user }}" 
      block:
        - name: Boostrap systemd units and sockets
          ansible.builtin.systemd:
            name: "{{ item.name }}"
            enabled: "{{ item.enabled }}"
            scope: "{{ item.scope }}"
          loop: "{{ baseos_gpg_systemd_user }}"

    - name: Pacakages
      become: true
      become_user: root
      block:
        - name: Install packages
          ansible.builtin.package:
            name: "{{ item }}"
          loop:
            - "{{ baseos_fedora_groups }}"
            - "{{ baseos_fedora_adhoc_rpms }}"

        - name: Updating to release
          ansible.builtin.dnf:
            name: "*"
            state: latest
            update_only: true
          register: __updated

        - name: Updated.results
          ansible.builtin.debug:
            var: __updated.results

        - name: Check if kernel was installed
          when: __updated.results is search("kernel")
          ansible.builtin.reboot:
            msg: "INFO: Kernel installed rebooting to load new kernel"
          register: __rebooted
