---
- name: Gathering facts
  ansible.builtin.gather_facts:

- name: Including Red Hat
  ansible.builtin.include_tasks: all.yml
  when:
    - inventory_hostname not in groups['network']
    - ansible_os_family == "RedHat"

- name: Include fedora
  ansible.builtin.include_tasks: fedora.yml
  when: 
    - ansible_distribution == "Fedora"
