---
- name: Gathering facts
  ansible.builtin.gather_facts:

- name: Including all
  ansible.builtin.include_tasks: all.yml
  tags: [baseos_ssh_keys, baseos_packages]
  when:
    - ansible_os_family == "RedHat"
    - inventory_hostname not in groups['network']

- name: Include fedora
  ansible.builtin.include_tasks: fedora.yml
  when: 
    - ansible_distribution == "Fedora"
