---
namespace: desyncit
name: baremetal
version: 1.0.0
readme: README.md
authors:
- Justin Herron <jherron@net-dev.net>
description: Collection of role to kick off a pxe boot of an OS via some baremetal management api.
license:
- CC-BY-4.0
tags:
  - collection
  - infrastructure
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null

