---
network_backup_dir_path: roles/network/files
network_backup_filename: config.backup
network_nmcli_bond:
  - { name: bond0, method4: disabled, method6: link-local, mode: 802.3ad, miimon: 100, xmit_hash_policy: layer2+3 }
network_nmcli_bond_slave:
  - { name: eno1, ifname: eno1, master: bond0 }
  - { name: eno2, ifname: eno2, master: bond0 }
network_switch_config:
  interfaces:
    - { name: Eth1/1, alias: to_host8_eno1, id: "8" }
    - { name: Eth1/2, alias: to_host8_eno2, id: "8" }
    - { name: Eth1/3, alias: to_host9_eno1, id: "9" }
    - { name: Eth1/4, alias: to_host9_eno2, id: "9" }
    - { name: Eth1/5, alias: to_host10_eno1, id: "10" }
    - { name: Eth1/6, alias: to_host10_eno2, id: "10" }
    - { name: Eth1/7, alias: to_host11_eno1, id: "11" }
    - { name: Eth1/8, alias: to_host11_eno2, id: "11" }
    - { name: Eth1/9, alias: to_host12_eno1, id: "12" }
    - { name: Eth1/10, alias: to_host12_eno2, id: "12" }
    - { name: Eth1/11, alias: to_host13_eno1, id: "13" }
    - { name: Eth1/12, alias: to_host13_eno2, id: "13" }
    - { name: Eth1/13, alias: to_host14_eno1, id: "14" }
    - { name: Eth1/14, alias: to_host14_eno2, id: "14" }
  lacp:
    - { id: "8", info: to_host8_bond0 }
    - { id: "9", info: to_host9_bond0 }
    - { id: "10", info: to_host10_bond0 }
    - { id: "11", info: to_host11_bond0 }
    - { id: "12", info: to_host12_bond0 }
    - { id: "13", info: to_host13_bond0 }
    - { id: "14", info: to_host14_bond0 }
