---
namespace: desyncit
name: general
version: 1.0.15
readme: README.md
authors:
- Justin Herron <jherron@net-dev.net>
description: Collection of general roles
license: 
  - CC-BY-4.0
tags:
  - infrastructure
  - collection
repository: https://github.com/desyncit/lab/issues 
