---
- name: Run scripts on managed nodes
  hosts: tests
  gather_facts: true

  vars:
    managed_scripts_repo:
     - name: Toolbox repo
       source: git@github.com:desyncit/toolbox.git
       dest: /var/tmp/toolbox
       update: yes
       force: true
       branch: main

    managed_scripts_manifest:
     - name: Checkonline for target hosts
       source: git@github.com:desyncit/toolbox.git
       target_hosts:
         - node01
       user: xasfg
       path: /var/tmp/toolbox/bash/bin/dummy.sh
       cron_enable: false
    
  roles:
    - managed_scripts
