---
- name: Validate IBM MQ Deployment
  hosts: tests
  gather_facts: true

  vars:

     mq_cluster:
       - name: MQIRINET
         qmgrs:
           - name: QM1
             host: node01
             listener_port: 1414
           - name: QM2
             host: node02
           - name: QM3
             host: node03
             listener_port: 1414

  roles:
    - mqclient
