---
storage_rbd_user: virt
storage_rbd_uuid: '{{ replace-me }}'

storage_ceph_release: "squid"
storage_cephadm_path: "/usr/bin/cephadm"
storage_cephadm_url: "https://download.ceph.com/rpm-{{ storage_ceph_release }}/el9/noarch/cephadm"

storage_auth_key_access: '/root/.ssh/id_ed25519.pub'
storage_auth_key_private: '/root/.ssh/id_ed25519'

# roles/network/var/main.yml
storage_machine_net: "{{ network_machine_net }}"
storage_cluster_net: "{{ network_cluster_net }}"

storage_grafana_port: '{{ replace-me }}'

storage_rgw_endpoint: '{{ replace-me }}'
storage_rgw_port: '{{ replace-me }}'
storage_rgw_ingress_port: "{{ replace-me }}"
storage_rgw_realm: "{{ replace-me }}"
storage_rgw_zonegroup: "us-east"
storage_rgw_zone: "madison"

storage_rgw_tls_state: false
storage_rgw_tls_private_key: 'None'
storage_rgw_tls_fullchain: 'None'

# needs regd container up
storage_rgw_ingress_regd:
  - name: "{{ replace-me }}"
    password: "{{ ansible_ssh_password }}"

storage_rgw_ingress_ips:
  - {{ replace-me }}

storage_osd_spec:
  - name: "{{ replace-me }}"
    model: "{{ replace-me }}"
    rotational: "{{ replace-me }}"
    crush_device_class: "{{ replace-me }}"
    label: "{{ replace-me }}"

storage_rgw_extra_args:
  - name: tcp_nodelay
    value: 1
  - name: max_header_size
    value: 65536

storage_mgr_modules:
  - { name: cephadm, state: enable }
  - { name: iostat, state: enable }
  - { name: prometheus, state: enable }
  - { name: restful, state: enable }
  - { name: rgw, state: enable }
  - { name: stats, state: enable }
  - { name: osd_perf_query, state: enable }

storage_orch_templates:
  - prometheus.yml.j2
  - node-exporter.yml.j2
  - rgw.yml.j2
  - rgw-ingress.yml.j2
  - grafana.yml.j2

storage_path_services: '/etc/ceph/services/'
storage_proxy_opts: "check observe layer4 error-limit 2 on-error mark-down inter 1s rise 5 slowstart 5s"
storage_haproxy_groups:
  frontend:
    - name: registry
      mode: tcp
      port: 5000
      port_args: 'ssl crt /var/lib/haproxy/haproxy.pem'
      options: ""
      default_backend: registry-api-gaspar-ontampa-dev
    - name: ingress-api-gaspar-ontampa-dev
      mode: tcp
      port: 6443
      port_args: ""
      options: "tcplog"
      default_backend: api-gaspar-ontampa-dev
    - name: ingress-machines-gaspar-ontampa-dev
      mode: tcp
      port: 22623
      port_args: ""
      options: "tcplog"
      default_backend: machines-gaspar-ontampa-dev
    - name: ingress-http-gaspar-ontampa-dev
      mode: tcp
      port: 80
      port_args: ""
      options: tcplog
      default_backend: http-gaspar-ontampa-dev
    - name: ingress-https-gaspar-ontampa-dev
      mode: tcp
      port: 443
      port_args: ""
      options: tcplog
      default_backend: https-gaspar-ontampa-dev
  backend:
    - name: registry-api-gaspar-ontampa-dev
      mode: tcp
      port: 5000
      balance: static-rr
      tag: registry
      server_opts: "check"
    - name: api-gaspar-ontampa-dev
      mode: tcp
      port: 6443
      balance: static-rr
      tag: api
      server_opts: "{{ storage_proxy_opts }}"
    - name: machines-gaspar-ontampa-dev
      mode: tcp
      port: 22623
      balance: static-rr
      tag: machines
      server_opts: "{{ storage_proxy_opts }}"
    - name: http-gaspar-ontampa-dev
      mode: tcp
      port: 80
      balance: static-rr
      tag: http
      server_opts: "{{ storage_proxy_opts }}"
    - name: https-gaspar-ontampa-dev
      mode: tcp
      port: 443
      balance: static-rr
      tag: https
      server_opts: "{{ storage_proxy_opts }}"
