FROM quay.io/lib/golang:1.24.4
COPY webroot /opt/webroot
WORKDIR /opt/webroot
COPY webroot/go.mod webroot/go.sum ./
RUN  go mod download && go mod verify
COPY . .
RUN go build -o server
CMD [ "./server" ]

