---
- name: VALIDATION
  become: true
  become_user: mqm
  block:

    - name: Get queue managers status
      queue_manager:
        qmname: "{{ qmgrs.name }}"
        state: status
        listener_port: "{{ qmgrs.listener_port | default(1414) }}"
      register: qm_status_registered
      loop: >-
        {{  mq_cluster 
          | map(attribute='qmgrs')
          | flatten
          | selectattr('host', 'equalto', inventory_hostname) 
          | list 
        }}
      loop_control:
        loop_var: qmgrs
      retries: "{{ retries | default(2) }}"
      delay: "{{ retry_delay | default(10) }}"
      until: 
        - ( qm_status_registered.status[qmgrs.name].qm_running is defined and
            qm_status_registered.status[qmgrs.name].listener_reachable is defined)

    - name: Assert Queue managers are up
      ansible.builtin.assert:
        that:
          - item.qm_running | bool
        fail_msg: "Assertion failed check {{ item.qm_name }}"
      loop: >-
        {{ qm_status_registered.results 
         | map(attribute='stdout') 
         | list 
        }}

    - name: Assert Queue managers are up
      ansible.builtin.assert:
        that:
          - item.listener_reachable | bool
        fail_msg: "Assertion failed listen socket {{ item.qm_name }} unreachable"
      loop: >-
        {{ qm_status_registered.results
         | map(attribute='stdout')
         | list
        }}
