---
- name: Bootstrap a Cluster
  become: true
  become_user: mqm
  block:

    - name: Generate the MQSC file on the remote node
      ansible.builtin.template:
        src: qm-cluster.mqsc.j2
        dest: "/var/mqm/config/qm-{{ qmgrs.name }}-cluster.mqsc"
        mode: '0644'
      loop: >-
        {{ mqclient_cluster 
         | map(attribute='qmgrs') 
         | sum(start=[]) 
         | selectattr('host', 'equalto', inventory_hostname) 
         | list 
        }}
      loop_control:
        loop_var: qmgrs

    - name: Apply configuration
      queue_manager:
        qmname: ["{{ qmgrs.name }}"] 
        state: running
        mqsc_file: "/var/mqm/config/qm-{{ qmgrs.name }}-cluster.mqsc"
      loop: >-
        {{ mqclient_cluster 
         | map(attribute='qmgrs') 
         | sum(start=[]) 
         | selectattr('host', 'equalto', inventory_hostname) 
         | list 
        }}
      loop_control:
        loop_var: qmgrs
