---
- name: Validate IBM MQ Deployment
  hosts: tests
  gather_facts: true

  vars:

     mq_cluster:
       - name: MQIRINET
         qmgrs:
           - name: NONE
             host: node01
             neighbors: []

  roles:
    - mqclient
