---
- name: Test cluster login
  kubernetes.core.k8s_cluster_info:
  register: cluster_info

- name: Show cluster info
  ansible.builtin.debug:
    var: cluster_info

- name: Fail if no namespaces returned
  when: cluster_info.resources | length == 0
  ansible.builtin.fail:
    msg: "Unable to connect to OpenShift cluster at {{ k8s_auth_api_key }}. Check your token and API URL."
