---
- name: Debug auth vars
  ansible.builtin.debug:
    msg:
      k8s_auth_host: "{{ k8s_auth_host | default('NOT SET') }}"
      k8s_auth_api_key: "{{ k8s_auth_api_key | default('NOT SET') }}"
      k8s_auth_verify_ssl: "{{ k8s_auth_verify_ssl | default('NOT SET') }}"

- name: Debug all variables
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]

- name: Getting cluster info
  community.okd.k8s:
    host: "{{ k8s_auth_host }}"
    api_key: "{{ k8s_auth_api_key }}"
    validate_certs: "{{ k8s_auth_verify_ssl }}"
    kind: Namespace
  register: cluster_info

- name: Fail if no namespaces returned
  when: cluster_info.resources | length == 0
  ansible.builtin.fail:
    msg: "Unable to connect to OpenShift cluster at {{ k8s_auth_api_key }}. Check your token and API URL."
