---
- name: Test cluster login
  kubernetes.core.k8s_cluster_info:
  register: gaspar_cluster_facts

- name: Verify login successful
  ansible.builtin.debug:
    msg:
      host: "{{ gaspar_cluster_facts.connection.host }}"
      api_version: "{{ gaspar_cluster_facts.version.server }}"

- name: Fail if no version returned
  ansible.builtin.assert:
    that:
      - cluster_facts.version.server is defined
      - cluster_facts.version.server | length > 0
    fail_msg: "Could not connect to cluster"
    success_msg: "Successfully connected to {{ gaspar_cluster_facts.connection.host }}"
