---
- name: Copy file to local path on remote host
  ansible.builtin.copy:
    src: "{{ copy_item.src }}"
    dest: "{{ copy_item.dest }}"
    owner: "{{ copy_item.owner }}"
    group: "{{ copy_item.group }}"
    mode: "{{ copy_item.mode }}"
    remote_src: true
  register: linux_common_manifest_copy_path_registered
  loop: >-
    {{ bwfu.files 
       | selectattr(
         'resource', 
         'equalto', 
         'file'
         ) 
       | list 
    }}
  loop_control:
    loop_var: copy_item
    label: >- 
      [local] [{{ copy_item.resource }}]
      {{ copy_item.src 
       ~ ' -> ' 
       ~ copy_item.dest 
      }}"

- name: Copy directory to local path on remote host
  ansible.builtin.copy:
    src: "{{ copy_item.src }}"
    dest: "{{ copy_item.dest }}"
    owner: "{{ copy_item.owner | default('root') }}"
    group: "{{ copy_item.group | default('root') }}"
    mode: "{{ copy_item.mode | default('0755') }}"
    remote_src: true
  register: linux_common_manifest_copy_path_dir_registered
  loop: >-
    {{ bwfu.files 
     | selectattr(
        'resource',
        'equalto', 
        'directory'
       ) 
     | list 
    }}
  loop_control:
    loop_var: copy_item
    label: "[directory] {{ copy_item.src ~ ' -> ' ~ copy_item.dest }}"
