---
- name: Check disk usage on remote host
  ansible.builtin.command:
    cmd: df {{ '-ah' if ansible_verbosity > 0 else '-h' }}
  register: linux_common_manifest_disk_registered
  changed_when: false
  no_log: true

- name: Display disk usage
  ansible.builtin.debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Disk Usage report:"
      - "{{ linux_common_manifest_disk_registered.stdout_lines }}"
