---
- name: Listing files in the specified paths
  ansible.builtin.command:
    cmd: ls {{ '-al' if ansible_verbosity > 0 else '' }} {{ bglz }}
  register: linux_common_manifest_list_registered
  changed_when: false
  loop: "{{ bwfu.paths | default([]) }}"
  loop_control:
    loop_var: bglz
  no_log: true

- name: Display registered results
  ansible.builtin.debug:
    msg: "{{ mani.stdout_lines }}"
  loop: "{{ linux_common_manifest_list_registered.results }}"
  loop_control:
    loop_var: mani
    label: "{{ inventory_hostname }} {{ mani.bglz }}"
