---
- name: Do generic task on RHEL hosts
  block:

    - name: Run asserts before doing anything
      ansible.builtin.include_tasks:
        file: checks.yml

    - name: Run task linux_common
      ansible.builtin.include_tasks:
        file: "{{ bwfu.task ~ '.yml' }}"
      loop: >-
        {{ linux_common_manifest
         | selectattr(
           'enabled',
           'equalto',
            true
           )
         | selectattr(
            'target_hosts',
            'contains',
            inventory_hostname
           )
         | list
        }}
      loop_control:
        loop_var: bwfu

