---
---
- name: Do generic task on RHEL hosts
  when: ansible_distribution == "RedHat"
  block:

    - name: Import checks before run
      ansible.builtin.import_tasks:
        file: checks.yml

    - name: Import compute tasks
      when: linux_generic_compute is defined
      ansible.builtin.import_tasks:
        file: compute.yml

    - name: Import storage tasks
      when: linux_generic_storage is defined
      ansible.builtin.import_tasks:
        file: storage.yml

    - name: Import network tasks
      when: linux_generic_network is defined
      ansible.builtin.import_tasks:
        file: network.yml
