---
- name: Apply permission changes to directories on remote host
  ansible.builtin.file:
    path: "{{ perm_item.path }}"
    owner: "{{ perm_item.owner }}"
    group: "{{ perm_item.group }}"
    mode: "{{ perm_item.mode }}"
    recurse: true
    state: directory
  register: linux_common_manifest_permissions_dir_registered
  loop: >-
    {{ bwfu.changes
     | selectattr(
        'type',
        'equalto',
        'directory'
       )
     | list
    }}
  loop_control:
    loop_var: perm_item
    label: "Applying changes to {{ perm_item.path }}"

- name: Apply permission changes to files on remote host
  ansible.builtin.file:
    path: "{{ perm_item.path }}"
    owner: "{{ perm_item.owner }}"
    group: "{{ perm_item.group }}"
    mode: "{{ perm_item.mode }}"
    state: file
  register: linux_common_manifest_permissions_file_registered
  loop: >-
    {{ bwfu.changes
     | selectattr(
        'type',
        'equalto',
        'file'
       )
     | list
    }}
  loop_control:
    loop_var: perm_item
    label: "Apply changes to {{ perm_item.path }}"

- name: Display directory permission change results
  ansible.builtin.debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Path: {{ perm_result.perm_item.path }}"
      - "Type: {{ perm_result.perm_item.type }}"
      - "Owner: {{ perm_result.perm_item.owner }}"
      - "Group: {{ perm_result.perm_item.group }}"
      - "Mode: {{ perm_result.perm_item.mode }}"
      - "Changed: {{ perm_result.changed }}"
  loop: "{{ linux_common_manifest_permissions_dir_registered.results | default([]) }}"
  loop_control:
    loop_var: perm_result
    label: "Changed permissions on directory {{ perm_result.perm_item.path }}"

- name: Display file permission change results
  ansible.builtin.debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Path: {{ perm_result.perm_item.path }}"
      - "Type: {{ perm_result.perm_item.type }}"
      - "Owner: {{ perm_result.perm_item.owner }}"
      - "Group: {{ perm_result.perm_item.group }}"
      - "Mode: {{ perm_result.perm_item.mode }}"
      - "Changed: {{ perm_result.changed }}"
  loop: "{{ linux_common_manifest_permissions_file_registered.results | default([]) }}"
  loop_control:
    loop_var: perm_result
    label: "Changed file permissions on {{ perm_result.perm_item.path }}"
