---
- name: Remove files on remote host
  ansible.builtin.file:
    path: "{{ remove_item.path }}"
    state: absent
  register: linux_common_manifest_remove_registered
  loop: "{{ bwfu.paths }}"
  loop_control:
    loop_var: remove_item
    label: "[{{ remove_item.resource | default('file') }}] {{ remove_item.path }}"
