---
- name: Reconfig ingress service
  block:

    - name: Pre task
      run_once: True
      when:
        - inventory_hostname in groups['_admin']
      ansible.builtin.include_tasks: pre.yml
      args:
        apply:
          delegate_to: lb01

    - name: Dropping a holy hand grenade
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ storage_path_services + item }}" 
        owner: root
        group: root
        mode: "0644"
      loop:
        - haproxy.cfg

    - name: Inserting haproxy userlist
      ansible.builtin.blockinfile:
        path: "{{ storage_path_services + item }}"
        marker: '# {mark} USERLIST' 
        insertafter: '^# marker registry userlist'
        block: '{{ lookup("template", "inject-haproxy-userlist.cfg.j2") }}'
      loop:
        - haproxy.cfg

    - name: Inserting cloud hosts
      ansible.builtin.blockinfile:
        path: "{{ storage_path_services + item }}" 
        marker: '# {mark} OKD Section'
        insertbefore: EOF
        block: '{{ lookup("template", "inject-haproxy.cfg.j2") }}'
      loop:
        - haproxy.cfg

    - name: Removing markers
      ansible.builtin.replace:
        path: "{{ storage_path_services + item }}"
        regexp: "^# END USERLIST$"
        replace: ""
      loop:
        - haproxy.cfg

    - name: Removing markers
      ansible.builtin.replace:
        path: "{{ storage_path_services + item }}"
        regexp: "^# BEGIN OKD Section"
        replace: ""
      loop:
        - haproxy.cfg

    - name: Removing lines that break haproxy
      ansible.builtin.replace:
        path: "{{ storage_path_services + item }}"
        regexp: "^# END OKD Section$"
        replace: ""
      loop:
        - haproxy.cfg

    - name: Set haproxy config key
      changed_when: true
      ansible.builtin.command:
        chdir: "{{ storage_path_services }}"
        argv:
          - /usr/bin/ceph
          - config-key
          - set
          - "{{ item.key }}"
          - -i
          - "{{ item.value }}"
      loop:
        - key: 'mgr/cephadm/services/ingress/haproxy.cfg'
          value: 'haproxy.cfg'

    - name: Kicking haproxy in the face
      ansible.builtin.shell: |
        ceph orch reconfig ingress.rgw.TampaDevs
        ceph orch restart ingress.rgw.TampaDevs
