---
- name: Ingress tasks
  block:

    - name: Take some preworkout
      run_once: True
      when:
      - inventory_hostname in groups['_admin']
      ansible.builtin.include_tasks: pre.yml
      args:
        apply:
          delegate_to: lb01

    - name: Include cloud and network vars
      ansible.builtin.include_vars:
        file: "{{ '../../' + item + '/vars/main.yml' }}"
      loop:
        - cloud
        - network

    - name: Enable mgr modules
      changed_when: true
      ansible.builtin.command:
        argv:
          - /usr/bin/ceph
          - mgr
          - module
          - "{{ item.state }}"
          - "{{ item.name }}"
      loop: "{{ storage_mgr_modules }}"

    - name: Generating service yaml
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ storage_path_services }}{{ item | replace('.j2', '') }}"
        force: True
      loop: "{{ storage_orch_templates }}"

    - name: Radosgw storage provider switch a roo
      block:

        - name: Do we have a TampaDevs Realm
          shell: 'radosgw-admin realm list --format=json'
          register: __rgw_info_realm

        - name: Processing the vorhees output
          set_fact:
            realm_state: "{{ __rgw_info_realm.stdout | from_json }}"

        - name: To fail or not to fail
          ansible.builtin.fail:
            msg: "Realm doth not EXIST"
          when: storage_rgw_realm not in realm_state.realms

      rescue:
        
        - name: Bootstraping rgw
          changed_when: true
          ansible.builtin.command:
            argv:
             - /usr/bin/ceph
             - rgw
             - realm
             - bootstrap
             - -i
             - "{{ storage_path_services + item }}"
          loop:
            - rgw.yml

    - name: Spread them haproxy conf
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ storage_path_services + item }}" 
        owner: root
        group: root
        mode: "0644"
      loop:
        - haproxy.cfg

    - name: Inserting haproxy userlist
      ansible.builtin.blockinfile:
        path: "{{ storage_path_services + item }}"
        marker: '# {mark} USERLIST' 
        insertafter: '^# marker registry userlist'
        block: '{{ lookup("template", "inject-haproxy-userlist.cfg.j2") }}'
      loop:
        - haproxy.cfg

    - name: Inserting cloud hosts
      ansible.builtin.blockinfile:
        path: "{{ storage_path_services + item }}" 
        marker: '# {mark} BRYAN SAYS HES A CLOUD GOD'
        insertafter: EOF
        block: '{{ lookup("template", "inject-haproxy.cfg.j2") }}'
      loop:
        - haproxy.cfg

    - name: Set haproxy config key
      changed_when: true
      ansible.builtin.command:
        chdir: "{{ storage_path_services }}"
        argv:
          - /usr/bin/ceph
          - config-key
          - set
          - "{{ item.key }}"
          - -i
          - "{{ item.value }}"
      loop:
        - key: 'mgr/cephadm/services/ingress/haproxy.cfg'
          value: 'haproxy.cfg'

    - name: Deploy ingress service
      ansible.builtin.command:
        chdir: "{{ storage_path_services }}"
        argv:
          - /usr/bin/ceph
          - orch
          - apply
          - -i
          - "{{ item }}"
      loop:
        - rgw-ingress.yml
