---
galaxy_info:
  author: Justin Herron
  description: Role to manage scripts on managed nodes
  company: Netdev LLC
  issue_tracker_url: https://github.com/desyncit/lab/issues
  license: CC-BY-4.0
  min_ansible_version: "2.15"
  galaxy_tags:
    - infrastructure
dependencies: []
