---
- name: DEPLOY TO BAREMETAL
  delegate_to: localhost
  block:
    - name: Idrac setting next boot to pxe boot
      ansible.builtin.command:
        argv:
          - /usr/bin/ipmitool
          - -I
          - lanplus
          - -vv
          - -H
          - "{{ item.mgmt }}"
          - -U
          - "{{ ipmi_idrac_user }}"
          - -P
          - "{{ ipmi_idrac_pass }}"
          - chassis
          - bootparam
          - set
          - bootflag
          - force_pxe
      loop: "{{ beaker_dell_idrac_map }}"
      when:
        - ansible_system_vendor == 'Dell Inc.'
        - item.name == inventory_hostname
      changed_when: true

    - name: IMM setting next boot to pxe boot
      ansible.builtin.command:
        argv:
          - /usr/bin/ipmitool
          - -vv
          - -H
          - "{{ item.mgmt }}"
          - -U
          - "{{ ipmi_imm_user }}"
          - -P
          - "{{ ipmi_imm_pass }}"
          - chassis
          - bootparam
          - set
          - bootflag
          - force_pxe
      loop: "{{ beaker_ibm_imm_map }}"
      when:
        - ansible_system_vendor == 'IBM'
        - item.name == inventory_hostname
      register: ipmi_debug_out
      failed_when: "'Set Boot Device to force_pxe' not in ipmi_debug_out.stdout"
      changed_when: true

    - name: Setting disklist variable for kickstart
      ansible.builtin.set_fact:
        disklist: "{{ ansible_devices[item].model }}"
      loop: "{{ ansible_devices.keys() | select('match', 'sd.*') | list }}"
      when: '"PERC" in ansible_devices[item].model'

    - name: Generating Kickstart configs
      ansible.builtin.template:
        src: ks.cfg.j2
        dest: "{{ beaker_kickstart }}"
        mode: "0444"

- name: BOOTSTRAP
  delegate_to: localhost
  block:
    - name: Seting beaker distro tree id
      ansible.builtin.set_fact:
        beaker_treeid: "{{ item.id }}"
      loop: "{{ beaker_rhel_release_id }}"
      when: release in item.name

    - name: Deploying
      ansible.builtin.debug:
        msg: "RHEL version {{ release }} distro-tree-id: {{ beaker_treeid }}"

    - name: Provisioning ( takes about 15-20 min) you might wanna go grab a beer.
      ansible.builtin.command:
        argv:
          - /usr/bin/bkr
          - system-provision
          - --hub
          - "{{ beaker_hub }}"
          - --kickstart
          - "{{ beaker_kickstart }}"
          - --distro-tree
          - "{{ beaker_treeid }}"
          - "{{ inventory_hostname }}"
      changed_when: true

    - name: Waiting for hosts to respond
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        search_regex: OpenSSH
        delay: 60
        timeout: 1200

    - name: Run house cleaning
      ansible.builtin.file:
        path: "{{ beaker_keytab_copy_to }}"
        state: absent

- name: Handing off to Base OS role
  ansible.builtin.include_role:
    name: baseos
  vars:
    baseos_provision: "y"
