---
- name: Prepare container environment
  when:
    - beaker_krb5_state != "0"
  delegate_to: localhost
  run_once: true
  block:
    - name: Copying keytab over to {{ beaker_keytab_copy_to }}
      ansible.builtin.copy:
        src: "{{ beaker_keytab }}"
        dest: "{{ beaker_keytab_copy_to }}"
        decrypt: true
        mode: "0644"

    - name: Getting kerberos ticket
      ansible.builtin.command:
        argv:
          - /usr/bin/kinit
          - -p
          - "{{ beaker_keytab_principal }}"
          - -k
          - -t
          - "{{ beaker_keytab_copy_to }}"
      changed_when: true

    - name: Checking krb5 ticket cache
      ansible.builtin.command:
        cmd: /usr/bin/klist -s
      register: beaker_krb5_state
      changed_when: true

    - name: Checking the state of kerberos
      ansible.builtin.fail:
        msg: Fail something went wrong with kerberos
      when: beaker_krb5_state.rc != 0
