---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  galaxy:
    collections:
      - name: ansible.posix
      - name: ansible.utils
      - name: kubernetes.core
      - name: community.general
      - name: containers.podman
      - name: fedora.linux_system_roles
  python:
    - ansible
    - kubernetes
    - aiohttp
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
additional_build_steps:
  prepend_base: |
    RUN $PKGMGR install -y python3-pip python3-devel sshpass 
    RUN pip install --upgrade pip setuptools
  prepend_galaxy: |
    RUN $PKGMGR makecache 
    RUN $PKGMGR install -y ansible-core 
