---
- name: CLUSTER NETWORK ON NODES
  when: ansible_system_vendor == "Dell Inc."
  block:
    - name: Configure interfaces for LACP on cluster hosts
      loop: "{{ network_nmcli_bond }}"
      community.general.nmcli:
        type: bond
        conn_name: "{{ item.name }}"
        method4: "{{ item.method4 }}"
        method6: "{{ item.method6 }}"
        mode: "{{ item.mode }}"
        miimon: "{{ item.miimon }}"
        xmit_hash_policy: "{{ item.xmit_hash_policy }}"
        state: present

    - name: Adding bond subordinate interfaces
      loop: "{{ network_nmcli_bond_slave }}"
      community.general.nmcli:
        type: bond-slave
        slave_type: bond
        conn_name: "{{ item.name }}"
        ifname: "{{ item.ifname }}"
        master: "{{ item.master }}"
        state: present

- name: If IBM Do nothing and move on
  when: ansible_system_vendor == "IBM"
  ansible.builtin.debug:
    msg: IBM host detected no need to mess with interfaces moving on
  changed_when: true

- name: If Supermicro do nothing and move on
  when: ansible_system_vendor == "Supermicro"
  ansible.builtin.debug:
    msg: Supermicro detected no need to mess with interfaces moving on
  changed_when: true
