---
- name: Configure host interfaces
  ansible.builtin.include_tasks: hosts.yml

- name: Configuring switch interfaces
  ansible.builtin.include_tasks: switch.yml
  when: inventory_hostname in groups['network']

- name: Backup of switch configuration
  ansible.builtin.include_tasks: backup.yml
  tags: network_backup_switch_config
  when: inventory_hostname in groups['network']
