---
- name: Configure network switch
  block:
    - name: Configure interface names
      loop: "{{ network_switch_config | dict2items | subelements('value') }}"
      when: item.0.key == 'interfaces'
      dellemc.enterprise_sonic.sonic_config:
        lines:
          - description {{ item.1.alias }}
        parents: ["interface {{ item.1.name }}"]
        save: true

    - name: Create the portchannels
      loop: "{{ network_switch_config | dict2items | subelements('value') }}"
      when: item.0.key == 'lacp'
      dellemc.enterprise_sonic.sonic_config:
        lines:
          - interface PortChannel {{ item.1.id }} mode active fast_rate

    - name: Setting portchannel descriptions
      loop: "{{ network_switch_config | dict2items | subelements('value') }}"
      when: item.0.key == 'lacp'
      dellemc.enterprise_sonic.sonic_config:
        lines:
          - description {{ item.1.info }}
        parents: interface PortChannel {{ item.1.id }}

    - name: Add interfaces to the previously created portChannels
      loop: "{{ network_switch_config | dict2items | subelements('value') }}"
      when: item.0.key == 'interfaces'
      dellemc.enterprise_sonic.sonic_config:
        lines:
          - no ipv6 enable
          - channel-group {{ item.1.id }}
        parents: interface {{ item.1.name }}

    - name: Writing running-config to startup
      dellemc.enterprise_sonic.sonic_config:
        save: true

    - name: Generating backup configuration
      ansible.builtin.include_tasks: backup.yml
