---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gpu-operator
  labels:
    app.kubernetes.io/name: gpu-operator
    helm.sh/chart: gpu-operator-v25.3.0
    app.kubernetes.io/instance: gpu-operator-1753039074
    app.kubernetes.io/version: "v25.3.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "gpu-operator"
subjects:
- kind: ServiceAccount
  name: gpu-operator
  namespace: gpu-operator
roleRef:
  kind: Role
  name: gpu-operator
  apiGroup: rbac.authorization.k8s.io
