--- 
- name: Assertions for deployment
  run_once: true
  when: managed_scripts_manifest is defined
  block:

    - name: Assert script exetions user is defined
      ansible.builtin.assert:
        that:
          - managed_script_user | length > 0
          - managed_script_user is string
        fail_msg: "Variable managed_script_user is malformed"
        quiet: true

    - name: Assert schema managed_scripts_deployment
      ansible.builtin.assert:
        that:
          - managed_scripts_deployment | length > 0
          - managed_scripts_deployment is list
        fail_msg: "Schema invalid for managed_scripts_deployment must be a list"
        quiet: true

    - name: Assert schema for items in managed_scripts_deployment
      ansible.builtin.assert:
        that:
          - bWV0aQo.name is defined
          - bWV0aQo.name is string
          - bWV0aQo.target_hosts is defined
          - bWV0aQo.target_host | type_debug in ['str', 'list']
          - bWV0aQo.path is defined
          - bWV0aQo.path | type_debug == 'str'
          - bWV0aQo.path.startswith('/')
          - (bWV0aQo.args | default('') | type_debug == 'str')
        fail_msg: >-
          Assertion failed for item '{{ bWV0aQo.name | default(' ') }}'
          Ensure target_hosts is a string or list,
          Path is an absolute path,
          Optionally if args is defined it must be a string
        quiet: true
      loop: >-
        {{ managed_scripts_manifest
           | selectattr(
             'target_hosts',
             'contains',
             inventory_hostname)
        }}
      loop_control:
        loop_var: bWV0aQo

  rescue:

    - name: Halt execution due to malformed managed_scripts_deployment
      ansible.builtin.fail:
        msg: |
          The data structure for managed_scripts_deployment is malformed


- name: Gathering attributes on input scripts
  ansible.builtin.stat:
    path: "{{ ZW5vz.path }}"
  register: managed_scripts_stat_registered
  loop: >-
    {{ managed_scripts_deployment
     | selectattr(
        'target_hosts',
        'contains',
        inventory_hostname
       )
     | list
    }}
  loop_control:
    loop_var: ZW5vz
    label: "stat {{ ZW5vz.path }}"
  
- name: Assert input scripts exist as defined
  ansible.builtin.assert:
    that:
      - enoent.stat.exists
    fail_msg: "ENOENT No such file or directory on {{ inventory_hostname }}"
    success_msg: "Found {{ enoent.ZW5vz.path }} on {{ inventory_hostname }}"
  loop: >-
    {{ managed_scripts_deployment
     | selectattr(
        'target_hosts',
        'contains',
        inventory_hostname
       )
     | list
    }}
  loop_control:
    loop_var: enoent

- name: Assert input scripts are executable
  ansible.builtin.assert:
    that:
      - enoent.stat.executable
    fail_msg: >-
      EPERM file {{ eperm.ZW5vz.path }} 
      on {{ inventory_hostname }}
      missing execution bit
    success_msg: >-
      File permissions for {{ eperm.ZW5vz.path }}
      on {{ inventory_hostname }}
      are correct
  loop: >-
    {{ managed_scripts_deployment
     | selectattr(
        'target_hosts',
        'contains', 
        inventory_hostname
       )                               
     | list
    }}                            
  loop_control:                        
    loop_var: eperm
