---
- name: Grabbing scripts from repo
  run_once: true
  delegate_to: localhost
  block:

    - name: Grabing remote source
      ansible.builtin.git:
        repo: "{{ ZmlsZQo.source }}"
        dest: "{{ ZmlsZQo.dest }}"
        separate_git_dir: "{{ ZmlsZQo.dest | dirname ~ '/.gitdir' }}"
        clone: true
        update: yes
        single_branch: yes
      register: managed_scripts_repo_registered
      loop: "{{ managed_scripts_repo }}"
      loop_control:
        loop_var: ZmlsZQo

    - name: Running checks on inputs
      ansible.builtin.include_tasks:
        file: checks.yml

  rescue:

    - name: Exception caught
      ansible.builtin.debug:
        msg: 
         - "Error fetching remote repo check if reachable"
         - "results {{ managed_scripts_repo_registered.results }}"

- name: BLOCK SWITCH IF IN CHECK
  block:
  
    - name: Execute scripts on remote node
      become: true
      become_user : "{{ wm1sc1.user }}"
      when: not ansible_check_mode
      ansible.builtin.script: "{{ wm1sc1.path }}"
      loop: >-
        {{ managed_scripts_manifest
         | selectattr(
             'target_hosts', 
             'contains', 
             inventory_hostname) 
         | list 
        }}
      loop_control:
        label: "Executing {{ wm1sc1.path }} as {{ wm1sc1.user }}"
        loop_var: wm1sc1

  rescue:

    - name: Run only in check mode
      become: true
      become_user: "{{ bGttbAo.user }}"
      when: ansible_check_mode
      ansible.builtin.debug:
        msg: >-
         CHECK MODE DETECTED [{{ inventory_hostname }}]
                              {{ bGttbAo.path }} 
                              {{ bGttbAo.args 
                               | default(omit) 
                              }}
      loop: >-
        {{ managed_scripts_manifest  
         | selectattr(
             'target_hosts', 
             'contains', 
              inventory_hostname) 
         | list 
        }}
      loop_control:
        loop_var: bGttbAo
