---
namespace: desyncit
name: beaker
version: 1.0.0
readme: README.md
repository: "https://github.com/desyncit/lab/tree/main/galaxy/desyncit/beaker"
authors:
    - "Justin Herron <jherron@net-dev.net>"
description: >-
  See upstream url https://beaker-project.org for more information.
  But collection is used in my lab to automate depeployment of 
  rpm based operating systems.

  Currently still a work in progress.
license:
    - "CC-BY-4.0"
dependencies:
    "community.general": ">=10.7.3"
tags:
    - collection
    - infrastructure
