---
- name: Main playbook
  hosts: "{{ host | default('all:!out') }}"
  gather_facts: true
  gather_subset:
    - os_family
    - hardware

  tasks:

    - name: tasks related to _self
      block:
        - name: Include baseos
          when:
            - _self_package is defined
          ansible.builtin.include_role:
            name: baseos

    - name: Provision the bare metal chassis.
      when:
        - inventory_hostname not in groups['network']
        - beaker_provision is defined
        - release is defined
      block:
        - name: Bootstraping the baremetal
          ansible.builtin.include_role:
            name: beaker

    - name: Provision the BaseOS.
      when: 
        - baseos_provision is defined
      block:
        - name: Deploying base configurations
          ansible.builtin.include_role:
            name: baseos
