---
- name: Main playbook
  any_errors_fatal: true
  hosts: "{{ host | default('all:!out') }}"

  tasks:

    - name: Provision the bare metal chassis.
      when:
        - inventory_hostname not in groups['network']
        - beaker_provision is defined
        - release is defined
      block:
        - name: Bootstraping the baremetal
          ansible.builtin.include_role:
            name: beaker

    - name: External Network provisioning
      when: 
        - network_provision is defined
      block:
        - name: Configuring bridge between cluster nodes
          when:
            - network_backup_switch_config is defined
          ansible.builtin.include_role:
            name: network

    - name: Downstream Servers
      when: 
        - baseos_provision is defined
      block:
        - name: Deploying base configurations
          when:
            - init_base is defined
          ansible.builtin.include_role:
            name: baseos

    - name: Cloud Environment deployment
      block:

      - name: Cloud or Domain Deployment
        when:
          - ( update_coreos is defined or
              deploy_domain is defined  )
        ansible.builtin.include_role:
          name: cloud
