---
managed_scripts_manifest:
  - name: List one
    path: /root/afile
    user: root
    target_hosts: localhost
    cron_enable: true
    cron_job: []
  - name: List two
    path: /root/bfile
    user: root
    target_hosts: irinetsys
    cron_enable: true
    cron_job: []
